// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description"`
	SellerName  *string `json:"sellerName"`
	Price       string  `json:"price"`
	Status      string  `json:"status"`
}

type Login struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type NewBook struct {
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type User struct {
	ID       *string `json:"id"`
	Username string  `json:"username"`
	Name     string  `json:"name"`
	Balance  *string `json:"balance"`
}
